// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"go_code/simplek8s/core/application/dao"
	"go_code/simplek8s/core/application/handler"
	"go_code/simplek8s/core/application/service"
	"go_code/simplek8s/internal/database"
	"go_code/simplek8s/server"
	"net/http"
)

// Injectors from wire.go:

func InitializeRouter() (http.Handler, error) {
	db := database.NewDB()
	clusterRepo := dao.NewClusterDao(db)
	clusterService := service.NewClusterService(clusterRepo)
	clusterHandler := handler.NewClusterHandler(clusterService)
	httpHandler := server.NewRouter(clusterHandler)
	return httpHandler, nil
}
